### ISSUE TITLE
auxiliar submodule uses invalid commit

### ISSUE THREAD

**Issue by squeek502** [zhaozg/lui#5]
`git submodule update` gives me the following error:

```
error: Server does not allow request for unadvertised object 0c1f37cf953e9a0520154443d49e94947de00969
Fetched in submodule path 'deps/auxiliar', but it did not contain 0c1f37cf953e9a0520154443d49e94947de00969. Direct fetching of that commit failed.
```

That commit hash is [viewable on Github](https://github.com/zhaozg/lua-auxiliar/tree/0c1f37cf953e9a0520154443d49e94947de00969) but [does not exist in the current history](https://github.com/zhaozg/lua-auxiliar/commits/master).

**Comment by zhaozg** [comment]
fix in https://github.com/zhaozg/lui/commit/d15aee77d886d33ee7bb99a658e2cd527b4c7659
